version: '3'

services:
  loadBalancer:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ./conf_load_balancer.d:/etc/nginx/conf.d
    links:
    - web1
    - web2
  web1:
    image: nginx:latest
    volumes:
    - ./public_html:/public_html
    - ./conf1.d:/etc/nginx/conf.d
    links:
    - php1
  php1:
    image: pasthortown/php:latest
    volumes:
    - ./public_html:/public_html
    links:
    - postgres
  web2:
    image: nginx:latest
    volumes:
    - ./public_html:/public_html
    - ./conf2.d:/etc/nginx/conf.d
    links:
    - php2
  php2:
    image: pasthortown/php:latest
    volumes:
    - ./public_html:/public_html
    links:
    - postgres
  postgres:
    image: postgres:latest
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres